### PR TITLE
Import TF2 Ultimate Visual Fix Pack

### PR DESCRIPTION
**Pull request by agrastiOs**
Tailored for TC2.

By popular demand and mastercom's request, the pack has been implemented for TC2.
https://github.com/agrastiOs/Ultimate-TF2-Visual-Fix-Pack

### CODE REVIEW

**Comment by Yttrium-tYcLief** [comment]
This is going to need some serious CLA review.

**Comment by melvyn2** [comment]
https://github.com/agrastiOs/Ultimate-TF2-Visual-Fix-Pack/graphs/contributors
Only 4 people to get ahold of, it seems.

**Comment by Yttrium-tYcLief** [comment]
That's the list of people that actually committed to the repo; does *all* of the code actually come from *only* them?

**Comment by mastercoms** [comment]
```
Thanks to the contributors:

    agrastiOs
    Nonhuman
    N-Cognito
    PieSavvy
    JarateKing
```

**Comment by agrastiOs** [comment]
Correct. Only one asset change was made by another person, who in fact worked on the original item either.

**Comment by Thestickman391** [comment]
I thought changing materials/models was out of scope for this project?

**Comment by Yttrium-tYcLief** [comment]
We're expanding the project a bit. That fact needs to be updated in documentation but it is happening.

**Comment by micwoj92** [comment]
> We're expanding the project a bit. That fact needs to be updated in documentation but it is happening.

Could there be "static" asset folder and executables separately? Some people would not want to download the same files over and over again.

**Comment by agrastiOs** [comment]
For the Discord question about the file size: this adds ~50 MB.

**Comment by Margen67** [comment]
> 
> 
> For the Discord question about the file size: this adds 49 MB.

That will add up to even more if more things keep getting added, and will slow down fetching the repository. imo game_clean should be put in a separate repository/branch, or this repo https://github.com/agrastiOs/Ultimate-TF2-Visual-Fix-Pack should have another branch for TC2.

**Comment by Yttrium-tYcLief** [comment]
I think a separate branch would *probably* be the best way to handle this, especially since, for development purposes, we *already* use a separate game install dir from the main repo dir.

**Comment by agrastiOs** [comment]
This pull request has been fully CLA reviewed and now ready for merging, aside from figuring out the best possible way to incorporate the pack.

**Comment by mastercoms** [comment]
Use the [new assets repo](https://github.com/mastercomfig/team-comtress-2-assets) to submit this PR.

**Pull request closed without merging**
