### PR TITLE
Re-Enable Player Gibbing in MvM

### PR DESCRIPTION
**Pull request by Thestickman391**
Not really sure why this is disabled...

### CODE REVIEW

**Comment by micwoj92** [comment]
Performance?

**Comment by Thestickman391** [comment]
Seems unlikely

**Comment by Yttrium-tYcLief** [comment]
This is going to need to be substantially performance tested, likely with a custom map, along with bugtested.

**Comment by Yttrium-tYcLief** [comment]
Sorry, I thought I was commenting on #126, my bad.

This one might have something to do with the reanimator and physics? Needs testing.

**Pull request closed without merging**
