### PR TITLE
Added jpeglib to windows game solution being generated, so it can be …

### PR DESCRIPTION
**Pull request by Zionner**
…compiled easily.

Modified instances of "libjpeg.lib" in VPCs and in the gitignore, to "jpeglib.lib", as this is the name of the library when manually compiled.

Also removed the binkw32 lib dependency, it doesn't seem to be doing anything.

### CODE REVIEW

**Comment by mrpotatofactory** [comment]
Are you sure the binkw32 library isn't being used for the start-up videos on 32-bit systems?

**Comment by Zionner** [comment]
I looked up the bink implementation, and it's all hidden behind a couple of global defines

`#if defined( BINK_VIDEO )

#if !defined( _GAMECONSOLE ) || defined( BINK_ENABLED_FOR_CONSOLE )`

A better implementation may be to conditionally include the library, based on these. Though I'm not familiar enough with VPC to say how feasible that is.

**Comment by mastercoms** [comment]
What is the benefit of compiling this?

**Comment by Zionner** [comment]
When I first tried compiling the project, I ran into a similar problem as was seen with this: https://github.com/mastercomfig/team-comtress-2/issues/20

One of the steps I took to fix this was to add the jpeglib to the solution. It doesn't fix missing crypto, or D3DX libs, but it removes  one of the problem libraries, since it's being compiled now.

**Comment by mastercoms** [comment]
I'll just include the lib file.

**Comment by Zionner** [comment]
Fair enough, thanks for taking a look.

**Pull request closed without merging**
