### PR TITLE
Revert sv_restrict_aspect_ratio_fov back to 1

### PR DESCRIPTION
**Pull request by Margen67**
This brings back Hor+ for 16:9> aspect ratios in fullscreen like in vanilla TF2.

### CODE REVIEW

**Comment by maximsmol** [comment]
Was this done on purpose? Can you link the commit where this regression occurred?

**Comment by Margen67** [comment]
https://github.com/mastercomfig/team-comtress-2/commit/9eaecc305f8d4eedd4a4bdc9c0a9caedbac1430f#diff-6e063ae7f62b003764d4eed06de1c2ebL243

**Comment by Yttrium-tYcLief** [comment]
While not explicitly mentioned in the commit description, this was explicitly highlighted in the patchnotes for 0.0.6, so I think it was intentional:

> `sv_restrict_aspect_ratio_fov 2` by default, so that players cannot gain an advantage with ultrawide displays

This is, as such, not a regression.

We can certainly have a discussion regarding if it should be changed back, but it's definitely not unintentional.

**Comment by Margen67** [comment]
> 
> 
> While not explicitly mentioned in the commit description, this was explicitly highlighted in the patchnotes for 0.0.6, so I think it was intentional:
> 
> > `sv_restrict_aspect_ratio_fov 2` by default, so that players cannot gain an advantage with ultrawide displays
> 
> This is, as such, not a regression.
> 
> We can certainly have a discussion regarding if it should be changed back, but it's definitely not unintentional.

The idea that 16:9> provides a "competitive advantage" is quite an unfortunate trend. I believe it started with incompetent video game companies like Blizzard intentionally doing this for Overwatch, etc. and people only defended them because they're bootlickers/fanboys that don't know any better, or don't care because they don't own an ultrawide display themselves.

If it were that much of a problem, and Valve cared, they would've done this already, especially for CS:GO.

Some games like [Far Cry 4](https://www.pcgamingwiki.com/wiki/Far_Cry_4#Video) even go so far as to lock the FOV completely for 21:9> which is completely ridiculous for a PC game. The FOV limit/zoom doesn't stop at 21:9, so at very wide aspect ratios like 3x16:9 (triple 1080p wide) the game becomes unplayable. This also applies here.

While it might provide a *slight* advantage, numerous other factors such as framerate, etc play a much bigger role, so it's a double standard to cap the FOV, but not, say, the framerate. Although the outcome of either is the same: The experience is worsened for arbitrary reasons.

I (and most other 16:9> users) would regard it as a regression/bug since it worsens the experience compared to the original game. In general, low FOV makes playing games unpleasant, so when games do this, people tend to try to fix it, even if it means bypassing anti-cheat(s). 16:9> displays are becoming more common so developers are slowly smartening up to this and supporting them natively.

The original value was a good compromise since it stops *anyone* from getting a higher FOV by making a window with a lower height. While this might inconvenience borderless fullscreen users, exclusive fullscreen gives you less input latency on Windows 8+/10 which otherwise force triple-buffered vsync, so it's not nearly as bad as also capping it in exclusive fullscreen making no workaround whatsoever possible.

**Comment by mastercoms** [comment]
> The original value was a good compromise since it stops anyone from getting a higher FOV by making a window with a lower height. While this might inconvenience borderless fullscreen users, exclusive fullscreen gives you less input latency on Windows 8+/10 which otherwise force triple-buffered vsync, so it's not nearly as bad as also capping it in exclusive fullscreen making no workaround whatsoever possible.

So by your logic, only those who pay for a wide screen monitor are allowed to have this privilege of natively having wider FOV? Plus, you can use custom resolutions on any monitor to get around the fullscreen restriction. Additionally, it is false that exclusive fullscreen gives less input latency. Microsoft has recommended using newer DX technologies which make exclusive fullscreen pretty much obsolete.

> If it were that much of a problem, and Valve cared, they would've done this already, especially for CS:GO.

All the being said, however, this is a good point, and I will revert it in the next release.

**Comment by Margen67** [comment]
> 
> 
> > The original value was a good compromise since it stops anyone from getting a higher FOV by making a window with a lower height. While this might inconvenience borderless fullscreen users, exclusive fullscreen gives you less input latency on Windows 8+/10 which otherwise force triple-buffered vsync, so it's not nearly as bad as also capping it in exclusive fullscreen making no workaround whatsoever possible.
> 
> So by your logic, only those who pay for a wide screen monitor are allowed to have this privilege of natively having wider FOV? Plus, you can use custom resolutions on any monitor to get around the fullscreen restriction.
> 

That still applies for 16:9 users, though. 16:10/4:3 users are still at a "disadvantage" (subjective since some actually stretch 4:3/16:10) because the Source engine doesn't compensate for the loss of FOV by increasing the FOV, or using letterboxed 16:9 like Overwatch.

And my point still stands: Why not cap the framerate too? It also provides an "advantage"

If you don't like people having an "advantage" over you, then why are you playing on a platform that's literally preferred because of customization?

**Comment by maximsmol** [comment]
Marking as `wontfix` and closing as maintainers are generally in agreement that we will not merge this. Feel free to reopen (or better yet create an issue) if you still think this is needed/want to discuss this more

**Pull request merged**
