### PR TITLE
Prevent Soul Gargoyle from leveling up on bots

### PR DESCRIPTION
**Pull request by Thestickman391**

### CODE REVIEW

**Review by maximsmol — APPROVED** [review]
LGTM

**Comment by mastercoms** [comment]
Is there a reason for disabling?

**Comment by Yttrium-tYcLief** [comment]
This is a cleaner overall implementation that would also inherently fix #161 at the same time. @mastercoms there's a longer discussion over on that other PR.

**Comment by Thestickman391** [comment]
I don't think that's true, #161 prevents MvM bots from spawning the souls, this just prevents bots from leveling up the gargoyle. If #161 isn't merged as well than you will still get the annoying soul particles in MvM, they just won't level up your gargoyle making them even more useless.

**Comment by Yttrium-tYcLief** [comment]
> I don't think that's true, #161 prevents MvM bots from spawning the souls, this just prevents bots from leveling up the gargoyle. If #161 isn't merged as well than you will still get the annoying soul particles in MvM, they just won't level up your gargoyle making them even more useless.

Sorry, I thought #202 also disabled the soul particles. Didn't look too closely at it.

Wouldn't it make sense to do that? Both for regular bots, and the side effect of benefitting MvM.

I'm all for a cleaner unified solution.

**Pull request closed without merging**
