### PR TITLE
Fix airblast being able to push detonating Sentry Busters

### PR DESCRIPTION
**Pull request by Thestickman391**

### CODE REVIEW

**Comment by Yttrium-tYcLief** [comment]
You say "fix" - how is this a bug?

**Comment by Thestickman391** [comment]
Normally, when Sentry Busters are taunting to detonate, they are immune to any form of knockback. However, they are not immune to the reworked airblast. Not only can this allow Pyros to save Engineers and push the explosion back at the robots, it allows trolling players to throw the detonating Buster at their teammates, killing them in the process.

**Comment by Thestickman391** [comment]
I should clarify that pre Jungle Inferno you were not able to airblast detonating sentry busters

**Comment by micwoj92** [comment]
@Thestickman391 TC2 has old airblast so this is not applicable here.

**Comment by Thestickman391** [comment]
Oops, my bad. I am dumb

**Comment by Yttrium-tYcLief** [comment]
Even if it was applicable here, this falls too much on the side of balance discussion to be within the scope of this project, IMO. While it might have become a thing thanks to a bug, it has real gameplay ramifications, both good and bad.

**Pull request closed without merging**
