### PR TITLE
Fix Spy bots using human voice lines in MvM

### PR DESCRIPTION
**Pull request by ghost**
While in the CTFBotSpyHide behavior, Spy bots always use Spy.TeaseVictim rather than Spy.MVM_TeaseVictim. This also fixes an error in the Spy.MVM_TeaseVictim soundscript.

### CODE REVIEW

**Comment by mastercoms** [comment]
Could you add a minimal extension to the sound script rather than providing the entire file? (it doesn't have to be working on its own, just enough text to be able to integrate)

**Comment by ghost** [comment]
Something like game_clean/copy/tf/tfc/scripts/game_sounds_vo_mvm_handmade.spybotfix.txt? Not quite sure what you mean

**Comment by mastercoms** [comment]
I don't mind any name, just the content of the file should be just the sound that you need, Spy.MvM_TeaseVictim (and anything else you need to add)

**Comment by ghost** [comment]
Updated

**Pull request closed without merging**
