### PR TITLE
Clean up third-party dependencies

### PR DESCRIPTION
**Pull request by melvyn2**
### Related Issue
Discord comment by mastercoms requesting the linux PR be split down.

### Implementation
The inflated amount of changes seen in the linux PR were due to dependencies being moved around, added, or deleted. These changes have been moved to this PR to make it easier to understand.

### Checklist

- [x] No other PRs implement this idea.
- [x] I certify that this PR is my own entirely original work, or I have permission from and have attributed the relevant authors.
- [x] I have agreed to and signed this project's [Contributor License Agreement](https://cla-assistant.io/mastercomfig/team-comtress-2).
- [ ] This PR only contains changes to the engine and/or core game framework
- [x] This PR targets the `community` branch.

- [ ] This change has been filed as an issue.
- [x] No other PRs address this.
- [ ] This PR is as minimal as possible.
- [ ] This PR does not introduce any regressions. (Pending testing)
- [ ] This PR has been built and locally tested on at least one platform. (Pending testing)
- [ ] This PR has been tested on all platforms, on both a dedicated server and on a listen server.

### Testing Checklist

|         |            Client             |            Server             | Version                     |
|---------|:-----------------------------:|:-----------------------------:|-----------------------------|
| Windows |  |  |     |
|   Linux |  |  |  |
|  Mac OS |  |  |       |

### Caveats
Slightly increases build times.

### Alternatives
Packaging every dependency as a pre-built binary,

### CODE REVIEW

**Comment by mastercoms** [comment]
I don't see any reason to remove protobuf 2.6.1.

**Comment by mastercoms** [comment]
Why is jpeglib renamed to libjpeg?

**Comment by melvyn2** [comment]
I remember that you had stated much earlier on that you wanted to use only 2.5.0 for all platforms, so 2.6.1 would be useless.

**Comment by mastercoms** [comment]
There's no reason to go around deleting files which have zero impact on the build. "Cleanliness" is this sense is a very useless concept.

**Comment by mastercoms** [comment]
Same goes for crypto++ 5.61. No reason to delete it.

**Comment by melvyn2** [comment]
By using system libraries, none of these changes are required any more.

**Pull request closed without merging**
