### PR TITLE
Add vanity bot names

### PR DESCRIPTION
**Pull request by maximsmol**
We should add the nicknames of major contributors, maybe also some references to community content and events. This is mostly to document the idea rather than to get this exact list merged.

### CODE REVIEW

**Comment by micwoj92** [comment]
please include mastercomfig contributors too 🥺👉👈

**Comment by MeDerpWasTaken** [comment]
Is that a overwatch advertisement?

**Comment by maximsmol** [comment]
> Is that a overwatch advertisement?

It's a Minecraft reference, the original is "Also try Terraria!"

**Comment by Yttrium-tYcLief** [comment]
It worked well for Minecraft because Minecraft was never endangered by Terraria. Maybe something more tongue-in-cheek might be appropriate?

"Also try Brink!"

**Comment by micwoj92** [comment]
When there are more cs:go things ported it should say Valorant.

**Comment by Yttrium-tYcLief** [comment]
To be clear, I honestly don't think this is appropriate to implement, but I figured the Brink joke was worth it. RFC.

**Comment by mrpotatofactory** [comment]
I would have agree with @Yttrium-tYcLief, I feel as though the bot names should be timeless and shouldn't use _meme culture_. I feel as though names which reference Valve games would be a much better addition.

**Pull request closed without merging**
