### PR TITLE
Fix ubercharge canteen running out cancelling Mmmpf taunt uber

### LINKED ISSUE #262: [MVM] Mphhh ubercharge canceling
### Description

If you use the "Become ubercharged" canteen, and when it's about to finish activate the "Mphhhh" effect from the phlogistinator, the ubercharge from the phlog will be cancelled

### Checklist

- [x] None of the open *or* closed issues document this problem.
- [x] This is a bug, not a new idea.
- [x] This is objectively a bug, and not something that people commonly disagree on.
- [x] This bug is in the code of the game, not in the textures, sounds, or other resources.
- [x] This issue occurs on the latest vanilla TF2 update.
- [ ] This issue is listed on the [Source 1 official bugtracker](https://github.com/ValveSoftware/Source-1-Games/issues).
- [ ] This issue occurs with DirectX level 100.
- [x] This issue occurs on the latest Team Comtress release, or the `master` branch.
- [x] This issue occurs when using no custom content.
- [x] This issue occurs when using `start_tf2.bat` (or `start_server.bat`) with no custom launch options.
- [x] This issue occurs when using a listen server (using the `map` command ingame).
- [ ] This issue occurs when using a dedicated server.
- [ ] This bug is in the internal procedures or tooling (e.g. the build process).

### Reproduction

1. Start a server with a MvM map.
2. Select pyro and equip the phlogistinator
3. Buy the ubercharge power-up
4. Start the wave and kill some robots to build up the mphhh meter
5. Once the mphhh meter is charged, activate the ubercharge.
6. Wait for about 3-4 seconds and then activate the mphhh effect.

### Setup Details
- *Server or client:*  Client.
- *Operating system:*  Windows 10
- *Team Comtress version:*  0.0.17
- *Custom content:*  None.
- *Launch options:*  None.
- *DirectX level:*  None.

### PR DESCRIPTION
**Pull request by Thestickman391**
Messy but fixes #262

### CODE REVIEW

**Comment by Yttrium-tYcLief** [comment]
I feel like this is so messy it might introduce a bunch of other bugs. Can anyone test it?

**Comment by joshuadinada** [comment]
I could try testing this, I'll let you know

**Comment by joshuadinada** [comment]
> I could try testing this, I'll let you know

Nvm I'm too stupid and didn't manage the building process

**Review by maximsmol — CHANGES_REQUESTED** [review]
This patch obviously makes it so Pyros never have their canteen Uber removed, since `!pTFPlayer->IsPlayerClass( TF_CLASS_PYRO )` is always false for them!

**Comment by Thestickman391** [comment]
Fixed

**Review by maximsmol — APPROVED** [review]
LGTM now

**Pull request closed without merging**
