### PR TITLE
fix CMake Error

### PR DESCRIPTION
**Pull request by micwoj92**
### Related Issue
N/A

### Solution
Remove zconf.h

### Screenshots

image

### Checklist

- [X] This PR targets the `master` branch.
- [ ] This bug has been filed as an issue.
- [X] No other PRs fix this bug.
- [X] This fix is as minimal as possible.
- [X] This fix does not introduce any regressions.
- [ ] This fix has been tested on all platforms, on both a dedicated server and on a listen server.

### Testing Checklist

|         |            Client             |            Server             | Version                     |
|---------|:-----------------------------:|:-----------------------------:|-----------------------------|
| Windows | built | built | Windows 8.1    |
|   Linux | N/A | N/A | N/A |
|  Mac OS | N/A | N/A | N/A      |

### Caveats
None that I know of.

### Alternatives
You can also edit CMakeList.txt https://github.com/mastercomfig/team-comtress-2/blob/master/thirdparty/zlib-1.2.5/CMakeLists.txt#L61

This error ocurred because of
image

### CODE REVIEW

**Comment by melvyn2** [comment]
what's the status on this? any reason for not merging?

**Comment by micwoj92** [comment]
> what's the status on this? any reason for not merging?
status 
image

**Comment by maximsmol** [comment]
Please explain why this error occurred, what other solutions you tried, all that jam

**Comment by micwoj92** [comment]
@maximsmol updated to make it 100% compatible with current templates.

**Comment by maximsmol** [comment]
Ok seems fine, but I don't understand why nobody else ran into this issue before. Unless someone can explain how to reproduce this, it will probably not be merged

**Comment by micwoj92** [comment]
I will restore that vm and try again later today. It was back when the build  instructions pointed to \thirdparty\protobuf-2.5.0\vsprojects\libprotobuf.vcproj so it probably is not even an issue now.

**Comment by micwoj92** [comment]
Doing the old install instuction from when this issue is made gives error, but after updating to d7acbf3 and redoing the install steps I could not reproduce it. So it maybe was the vcproj issue, no idea. But anyway, it no longer is issue so closing.

**Pull request closed without merging**
