### PR TITLE
Linux build support

### PR DESCRIPTION
**Pull request by melvyn2**
### Related Issue
#2

### Implementation
Creates 3 scripts to compile, symlink live assets, and run team comtress 2. It also fixes some incompatibilities, and forces some previously already-compiled dependencies to be compiled by the user (this can fix some incorrect paths, and allows us to edit those dependencies if needed). 
Work is currently being done to finalize the reverse-engineered vphysics source, which is why this is a draft.

### Screenshots
Screenshot_2020-10-25_17-35
Screenshot_2020-10-27_09-01

### Checklist

- [ ] No other PRs implement this idea. (There are, but they are outdated)
- [ ] This PR does not introduce any regressions. (Needs testing)
- [x] I certify that this PR is my own entirely original work, or I have permission from and have attributed the relevant authors.
- [x] I have agreed to and signed this project's [Contributor License Agreement](https://cla-assistant.io/mastercomfig/team-comtress-2).

- [x] This PR targets the `master` branch.
- [x] This change has been filed as an issue.
- [ ] No other PRs address this.
- [ ] This PR is as minimal as possible.
- [ ] This PR does not introduce any regressions.
- [x] This PR has been built and locally tested on at least one platform.
- [ ] This PR has been tested on all platforms, on both a dedicated server and on a listen server.

### Testing Checklist

|         |            Client             |            Server             | Version                     |
|---------|:-----------------------------:|:-----------------------------:|-----------------------------|
| Windows | Tested | Pending testing | Unknown, contact @Yttrium-tYcLief for details |
|   Linux | Tested | Failing | `5.8.16-lqx1-4-lqx #1 ZEN SMP PREEMPT Wed, 21 Oct 2020 18:15:28 +0000` |
|  Mac OS |  |  |       |

### Caveats
 - VPhysics Implementation is not complete
 - Dedicated servers do not work
 - Link Time Optimization does not work due to invalid relocations (from position-dependent code, which should not be in these `.so`s); these stop `lld` or `gold` from being used, which are required for LTO
 - Position Independent Code breaks almost everything (both `-fpic` and `-fPIC`): The game loads, but segfaults on loading into a map or server.
 - ~~Mathlib optmizations are broken~~ (fixed)
 - Dependencies bundled with the game are not being copied to the game folder
 - Random black line appears on the right side of the screen
 - Stack protection is disabled (Fix on GCC builds, broken in clang)
 - ~~GCC builds do not work~~ (fixed)
 - SteamRT builds do not work
 - Random segfaults/hangs everywhere (prevents benchmarking)
 - HDR or some other post processing turns the screen translucent brown
 - https://github.com/mastercomfig/team-comtress-2/issues/408#issuecomment-716250428

### Alternatives
Dropping linux as a supported platform.

### Credits
Obviously, I didn't do this all alone; thanks:
 - maximsmol, for starting this effort and for some patches still used
 - @HurricanePootis, for helping everywhere on this project and testing
 - @int-72h for testing and script updates
 - @CRACKbomber for almost the entirety of the VPhysics reversal project
and probably more people I forgot

### CODE REVIEW

**Comment by int-72h** [comment]
Testing build now- if successful I'll update the wiki.

**Comment by int-72h** [comment]
Successfully built on Arch Linux `` 5.9.1-5-tkg-MuQSS``.
Any bug reports for this untill merged should be on HurricainePootis's repo.

**Comment by int-72h** [comment]
Updated the build instructions on the wiki

**Comment by melvyn2** [comment]
Random progress report: GCC building is fixed.
 - The IVP linker issues were because of a bad `#pragma` (removed)
 - VGui2 clicks not registering were because a check in the click handler was badly optimized by GCC (set `-O0` for that function)

**Comment by int-72h** [comment]
Another quite critical bug is that the game segfaults when inspecting weapons.
This appears to be a faulty call of `KeyValues::WriteBinary` where it accesses a faulty member and crashes.
I'm investigating currently.

**Comment by int-72h** [comment]
I'm happy to say, ``KeyValues::WriteAsBinary`` is now fixed.
Also, building on anything besides are was questionable before (max got it to work on Nixos?) but I have successfully built inside an Ubuntu docker container, so it should be possible to build on any distro.

**Comment by int-72h** [comment]
Update: Another user has successfully compiled it on Ubuntu, and it seems to run.
Only major thing left is vphysics' ragdoll implementation, there is an assorted box of GUI segfaults (i.e when trying to use the matchmaker) but these are trivial.

**Comment by int-72h** [comment]
@Margen67 Is testing CI for the linux build currently.
Performance is questionable, and the assorted segfaults are deep within the material system due to memory issues with rendering displacements, so I can't fix those.

**Comment by int-72h** [comment]
...Turns out that segfault has always been there with Suijinbench. 
Performance is still poor, but it should be up to feature parity with upstream now - apart from ragdoll physics.

**Comment by melvyn2** [comment]
> ...Turns out that segfault has always been there with Suijinbench.
> Performance is still poor, but it should be up to feature parity with upstream now - apart from ragdoll physics.

Could you clarify a bit? Is there a segfault in suijinbench that also occurs on windows, or something else?

**Comment by melvyn2** [comment]
Oh, also forgot to post this. I did some benchmarking a couple days ago. While not as great as windows, there is still a nice improvement. More testing is greatly appreciated, and I will add a guide on how to do so properly soon.
[https://flightlessmango.com/games/21786/logs/1104](https://flightlessmango.com/games/21786/logs/1104)

**Comment by int-72h** [comment]
> > ...Turns out that segfault has always been there with Suijinbench.
> > Performance is still poor, but it should be up to feature parity with upstream now - apart from ragdoll physics.
> 
> Could you clarify a bit? Is there a segfault in suijinbench that also occurs on windows, or something else?

@Kenajcrap told me suijinbench *always* crashes after a bit- before I assumed this was a Linux specific issue but if it's a TC2 issue then luckily it's out of scope for this specific PR.

**Comment by melvyn2** [comment]
> > > ...Turns out that segfault has always been there with Suijinbench.
> > > Performance is still poor, but it should be up to feature parity with upstream now - apart from ragdoll physics.
> > 
> > 
> > Could you clarify a bit? Is there a segfault in suijinbench that also occurs on windows, or something else?
> 
> @Kenajcrap told me suijinbench _always_ crashes after a bit- before I assumed this was a Linux specific issue but if it's a TC2 issue then luckily it's out of scope for this specific PR.

That's strange; playing the whole `suijinbench.dem` simply brings me back to the main menu, where I can run it again. This might be a configuration-specific issue?

**Comment by int-72h** [comment]
> > > > ...Turns out that segfault has always been there with Suijinbench.
> > > > Performance is still poor, but it should be up to feature parity with upstream now - apart from ragdoll physics.
> > > 
> > > 
> > > Could you clarify a bit? Is there a segfault in suijinbench that also occurs on windows, or something else?
> > 
> > @Kenajcrap told me suijinbench _always_ crashes after a bit- before I assumed this was a Linux specific issue but if it's a TC2 issue then luckily it's out of scope for this specific PR.
> 
> That's strange; playing the whole `suijinbench.dem` simply brings me back to the main menu, where I can run it again. This might be a configuration-specific issue?

The segfault was deep within the material system during a `free()`. I don't think it was a config issue.

**Comment by int-72h** [comment]
Due to mastercoms' recent decision to take the game-related development private, I'm unsure about the future of this PR as it is mainly engine changes and bug fixes.

**Comment by micwoj92** [comment]
Team Comtress 2: Community Edition

**Comment by Margen67** [comment]
> 
> 
> Due to mastercoms' recent decision to take the game-related development private, I'm unsure about the future of this PR as it is mainly engine changes and bug fixes.

**Comment by int-72h** [comment]
For anyone wanting to test it, at the moment it is pseudostable - as long as you disable ragdoll physics.
Precompiled builds haven't been generated yet though.

**Comment by mastercoms** [comment]
> Due to mastercoms' recent decision to take the game-related development private, I'm unsure about the future of this PR as it is mainly engine changes and bug fixes.

Wouldn't the fact it _is_ mainly engine changes and bug fixes mean that it is still relevant to the project? Sorry, but I am not sure if I understand. This PR is totally valid for the project. Linux builds _are_ working internally without many changes. I just want to clarify: I _am_ accepting engine changes. I am _not_ accepting game changes.

**Comment by Xinayder** [comment]
I want to ask, why has the Linux support become so complicated? There was a PR a few months ago that worked (well, you could at least get the game running and test), and it didn't require 1/3 of the steps this new PR requires. What happened?

**Comment by micwoj92** [comment]
> I want to ask, why has the Linux support become so complicated? There was a PR a few months ago that worked (well, you could at least get the game running and test), and it didn't require 1/3 of the steps this new PR requires. What happened?

People were not agreeing.

**Comment by int-72h** [comment]
> I want to ask, why has the Linux support become so complicated? There was a PR a few months ago that worked (well, you could at least get the game running and test), and it didn't require 1/3 of the steps this new PR requires. What happened?

That PR was a bit of a mess - a refactor was needed to "tidy it up". As well, coms made some optimisations which completely broke linux support, and we (namely crackbomber) had to reverse engineer another leak for the physics engine to get it to work again. This PR is a bit more centralised as well, for lack of a better word. At the moment, `vphysics-rev` is the most "working" branch at the moment, considering effectively most of vphysics has been RE'd but not all of it - hence this is still a draft.

**Comment by int-72h** [comment]
@CRACKbomber any update on vphysics?

**Comment by CRACKbomber** [comment]
@int-72h yes, getting back into the saddle now. We have a new home for development on it. We are working off a custom 2008 branch and doing the RE there. Add me on discord and I can fill you in. crackbomber#0540

**Comment by Sirbucket** [comment]
So far it has failed to build on fedora 33 with what I know as are the correct dependencies, I put the error log in the branches issues page.

**Comment by Sirbucket** [comment]
I could be dumb and just did it wrong but from what I saw it just refused to work and certain paths that are supposed to build don't build on fedora.

**Comment by melvyn2** [comment]
superseded by #603

**Pull request closed without merging**
