### PR TITLE
mp_friendlyfire 1 fixes

### PR DESCRIPTION
**Pull request by Margen67**
### Related Issue
#243

### Implementation
Adds checks for `mp_friendlyfire`.

### Checklist
- [x] This PR targets the `master` branch.
- [ ] This change has been filed as an issue.
- [x] No other PRs address this.
- [x] This PR is as minimal as possible.
- [ ] This PR does not introduce any regressions.
- [ ] This PR has been tested on all platforms, on both a dedicated server and on a listen server.

### Testing Checklist
|         |            Client             |            Server             | Version                     |
|---------|:-----------------------------:|:-----------------------------:|-----------------------------|
| Windows |  |  |     |
|   Linux |  |  |  |
|  Mac OS |  |  |       |

### Caveats
read commits

### CODE REVIEW

**Comment by MarkJGx** [comment]
Should be
```cpp
if ( pTarget && (pTarget->GetTeamNumber() != pPlayer->GetTeamNumber() || friendlyfire.GetInt()))
```
to avoid deref null

**Comment by Margen67** [comment]
> 
> 
> Should be
> 
> ```c++
> if ( pTarget && (pTarget->GetTeamNumber() != pPlayer->GetTeamNumber() || friendlyfire.GetInt()))
> ```
> 
> to avoid deref null

Ok.

#
All tauntkills except Armageddon now work, along with the Flying Guillotine, Mad Milk/Jarate*, Sandman projectiles, and the Holiday Punch not forcing teammates to laugh.

However, Mad Milk/Jarate get applied to the thrower, and doesn't apply the breadmonster to teammates.

**Review by maximsmol — APPROVED** [review]
LGTM

**Comment by Margen67** [comment]
Pushed a fix for arrows. (Crusader's Crossbow/Huntsman)
The Huntsman doesn't work at close range, but it's better than nothing.

**Comment by wgetJane** [comment]
> Pushed a fix for arrows. (Crusader's Crossbow/Huntsman)
> The Huntsman doesn't work at close range, but it's better than nothing.

this might be useful: https://github.com/ldesgoui/tf2-comp-fixes/blob/master/INTERNALS.md#fix-ghost-crossbow-bolts--projectiles-ignore-teammates

**Comment by Margen67** [comment]
I had an idea. What if there was a "complete" and "partial" mode for mp_friendlyfire?
i.e. you can only airblast teammates if mp_friendlyfire is set to 2 or something

**Comment by Margen67** [comment]
I've pushed more fixes, and reverted the tf_weapon_jar.cpp changes since it applies to the thrower.

I also added links to most of the code in #243.

**Comment by Margen67** [comment]
Flying Guillotine, Mad (Mutated) Milk, and Jarate (Self-Aware Beauty Mark) are now fully fixed.

**Comment by Margen67** [comment]
Pushed fixes for Flamethrower and arrows.

**Pull request closed without merging**
