### PR TITLE
Add support for F13-F24 buttons

### PR DESCRIPTION
**Pull request by treacherousfiend**
### Related Issue
#277 Add support for more mouse buttons

### Implementation
Add baseline support for F13-F24, Extra mouse button support seems impossible since its not a thing defined in the OS.
If you have a mouse with mouse buttons 6-9 you can most likely rebind them to these new F keys anyway

### Screenshots
N/A

### Checklist

- [x] This PR targets the `master` branch.
- [x] This change has been filed as an issue.
- [x] No other PRs address this.
- [x] This PR is as minimal as possible.
- [x] This PR does not introduce any regressions.
- [ ] This PR has been tested on all platforms, on both a dedicated server and on a listen server.

### Testing Checklist

|         |            Client             |            Server             | Version                     |
|---------|:-----------------------------:|:-----------------------------:|-----------------------------|
| Windows | Tested | N/A | Windows 10  |
|   Linux | N/A | N/A | N/A |
|  Mac OS | N/A | N/A | N/A |

### Caveats
Currently the F13-F24 buttons only work when the console is open, suggestions to fix this would be very nice
The new keys can only be bound via the console, attempting to bind them via settings gives the same result that the escape key  gives.

### Alternatives
None

### CODE REVIEW

**Comment by Yttrium-tYcLief** [comment]
> Currently the F13-F24 buttons only work when the console is open, suggestions to fix this would be very nice

This definitely needs to be addressed before I'd feel comfortable merging this.

**Comment by treacherousfiend** [comment]
Agreed, this PR is not ready for merging yet, I simply posted it in the hopes that someone could help troubleshoot since my knowledge is super limited.

**Comment by Yttrium-tYcLief** [comment]
> Agreed, this PR is not ready for merging yet, I simply posted it in the hopes that someone could help troubleshoot since my knowledge is super limited.

Totally fine! Was just making sure that stance is firm so nobody else merges it either.

**Comment by treacherousfiend** [comment]
edited caveats section to address another bug I remembered

**Comment by Yttrium-tYcLief** [comment]
implemented in #356 (779e624)

**Pull request closed without merging**
