### PR TITLE
Disable Halloween soul drops in MvM mode

### PR DESCRIPTION
**Pull request by Thestickman391**

### CODE REVIEW

**Comment by Yttrium-tYcLief** [comment]
this one might be a bit controversial, need a ruling

**Comment by Kenajcrap** [comment]
Halloween souls dropping from MVM bots feels very much unintentional on a lore/cosmetic approach (since robots don't have souls) and look abnoctious during play because of the amount of them floating around.

**Comment by mrpotatofactory** [comment]
I don't think this should be changed as the robots could very well be replaced as zombies or some other model replacement. This change could break community maps or gamemodes which rely on such customisations.

**Comment by Yttrium-tYcLief** [comment]
You could use a server convar (`mvm_enable_halloween_souls`?) to enable/disable soul collection in MvM, defaulted to `0`, but community servers could set it to `1`.

**Comment by Thestickman391** [comment]
Are there community servers that rely on halloween soul drops?

**Comment by maximsmol** [comment]
I think this is unintentional too. Does this influence the Gargoyle btw?

**Comment by Thestickman391** [comment]
It does influence the Gargoyle but thats another bug, it really shouldn't level up on bots

**Review by maximsmol — APPROVED** [review]
Changes LGTM btw. @Yttrium-tYcLief (pinging you since you already commented) I think we should merge this since nobody really said anything against this change

**Pull request closed without merging**
