### PR TITLE
Update the Valve intro to post 2011 one

### PR DESCRIPTION
**Pull request by Thestickman391**

### CODE REVIEW

**Comment by micwoj92** [comment]
I do not think this is in scope of this project, also, what is .gitkeep????

**Comment by geniiii** [comment]
Rebasing and removing the .gitkeep commits would be nice.

**Comment by HurricanePootis** [comment]
Couldn't you already do this without changing anything in the code? I think it would be nicer for the end user the decide if they want to change the valve intro.

**Comment by maximsmol** [comment]
Does live TF2 use the new or the old intro?

**Comment by agrastiOs** [comment]
> 
> 
> Does live TF2 use the new or the old intro?

live TF2 uses the old.

**Comment by Yttrium-tYcLief** [comment]
This is definitely outside the scope of this project.

**Comment by maximsmol** [comment]
Yeah this is wontfix

**Pull request closed without merging**
