### PR TITLE
 Import ZoraKirby's Proper Thirdperson All-Class Melee Animations for Engineer

### PR DESCRIPTION
**Pull request by Thestickman391**
Stolen from https://gamebanana.com/skins/166241

### Related Issue
#394 

### Implementation
Just taking the files from the mod and adding them to the tc2 folder in game_clean/custom

### Checklist

- [x] This PR targets the `master` branch.
- [x] This change has been filed as an issue.
- [x] No other PRs address this.
- [x] This PR is as minimal as possible.
- [x] This PR does not introduce any regressions.
- [x] This PR has been tested on all platforms, on both a dedicated server and on a listen server.

### Testing Checklist

|         |            Client             |            Server             | Version                     |
|---------|:-----------------------------:|:-----------------------------:|-----------------------------|
| Windows | Built, Tested | Built | Windows 10 |
|   Linux |  |  |  |
|  Mac OS |  |  |       |

### Caveats
None

### Alternatives
Editing player/engineer_animations.mdl instead of player/engineer_user_animations.mdl

### CODE REVIEW

**Comment by micwoj92** [comment]
Needs CLA

**Comment by Thestickman391** [comment]
@zorakirby

**Comment by zorakirby** [comment]
I have a more updated version of these animations. I implemented the animations very awkwardly on the versions on gamebanana and on the workshop (basically, these are gunslinger animations and a single pose animation combined together with spaghetti qc code). I have since edited all the melee_allclass smd animations themselves so that in theory, no qc code needs to be changed and the all-class melee animation smd/dmx files can just be replaced, but never got around to updating the workshop file or gamebanana submission because there are still some small changes I needed to do. Right now these are all in smd format and are named exactly what decompiling the animation files gave me so they may not match what Valve has on their end. I can make any changes required to make these compatible, however I am currently in a different location than the computer that has these files and I will be back in ~2 days.

**Comment by Yttrium-tYcLief** [comment]
1. CLA and proper authorization
2. Let's hold off on asset PRs until we decide how we're going to handle assets

**Comment by mastercoms** [comment]
I am not going to be accepting decompiled animation fixes, nor does Valve have a history of accepting them.

**Comment by zorakirby** [comment]
Is there any other way to submit animation fixes?

**Comment by mastercoms** [comment]
I can't say for sure, but the only cases where it would seem acceptable to me would be by using the Valve sources, which obviously isn't possible.

**Comment by zorakirby** [comment]
If there does end up being a way, please let me know, I would love to get these fixes submitted somehow.

**Comment by Malfunktion-issues** [comment]
Ah, well, it was worth a try.

**Comment by zorakirby** [comment]
I believe I have figured out a way of implementing this that doesn't involve submitting decompiled files, as in, would be only an mdl submission, and does not modify engineer_user_animations, but as Yttrium mentioned, we would need to decide how asset PRs would be handled first.

**Pull request closed without merging**
